kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Forward the NodePort (30725) to the host's port (30725)
  extraPortMappings:
  - containerPort: 30725
    hostPort: 30725
    listenAddress: "0.0.0.0"
    protocol: TCP