apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend      # <--- Crucial link!
  ports:
    - protocol: TCP
      port: 80      # The port the Service listens on
      targetPort: 5000 # The port the Container is listening on